# Generated by Django 5.1.3 on 2024-12-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_auth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='auth_token',
        ),
    ]
