# Generated by Django 5.1.3 on 2024-12-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_created_at_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
