version: '3.8'

services:
  web:
    build: .
    container_name: ollayor-courses-bot
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://ollayor:postgres@db:5432/porla_course_bot
      - API_TOKEN=${API_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
    command: >
      sh -c "python admin_panel/manage.py collectstatic --noinput &&
             python admin_panel/manage.py runserver 0.0.0.0:8000 &
             python app.py"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ollayor
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: porla_course_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: