# Generated by Django 5.1.3 on 2025-03-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprogress",
            name="unlocked_by_quiz",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this lesson was unlocked by completing a previous quiz perfectly",
            ),
        ),
    ]
