# Generated by Django 5.1.3 on 2024-11-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='telegram_xideo_id',
            new_name='telegram_video_id',
        ),
    ]
