# Generated by Django 5.1.3 on 2024-11-10 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_price_to_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Course price in UZS', max_digits=9, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
