# Generated by Django 5.1.3 on 2024-12-16 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='telegram_video_unique_id',
            field=models.CharField(default=django.utils.timezone.now, help_text='Unique identifier for video', max_length=255, verbose_name='Video Unique ID'),
            preserve_default=False,
        ),
    ]
