# Generated by Django 5.1.3 on 2024-12-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_lesson_telegram_video_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='telegram_video_id',
            field=models.CharField(blank=True, help_text='Video ID from Telegram', max_length=255, null=True, verbose_name='Telegram Video ID'),
        ),
    ]
