# Generated by Django 5.1.3 on 2025-03-22 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "profile_picture_id",
                    models.CharField(
                        help_text="Profile picture ID from Telegram",
                        max_length=255,
                        verbose_name="Mentor picture ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mentor",
                "verbose_name_plural": "Mentors",
            },
        ),
        migrations.CreateModel(
            name="MentorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="mentors.mentor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mentor Availability",
                "verbose_name_plural": "Mentor Availability",
                "ordering": ["start_time"],
            },
        ),
    ]
