# Generated by Django 5.1.3 on 2024-11-18 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mentoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='profile_picture_id',
            field=models.CharField(default=django.utils.timezone.now, help_text='Profile picture ID from Telegram', max_length=255, verbose_name='Mentor picture ID'),
            preserve_default=False,
        ),
    ]
