# Generated by Django 5.1.3 on 2024-11-24 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_mentor_profile_picture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoravailability',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
