# Generated by Django 5.1.3 on 2024-12-16 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_mentoravailability_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='profile_picture_unique_id',
            field=models.CharField(default=django.utils.timezone.now, help_text='Unique identifier for profile picture', max_length=255, verbose_name='Picture Unique ID'),
            preserve_default=False,
        ),
    ]
