# Generated by Django 5.1.3 on 2024-12-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0005_mentor_profile_picture_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='profile_picture_unique_id',
        ),
    ]
