# Generated by Django 5.1.3 on 2024-12-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_remove_mentor_profile_picture_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='profile_picture_id',
            field=models.CharField(blank=True, help_text='Profile picture ID from Telegram', max_length=255, null=True, verbose_name='Mentor picture ID'),
        ),
    ]
